services:
  postgres-db:
    image: postgres:16
    container_name: postgres-spring-security
    environment:
      POSTGRES_DB: administradorUsuariosDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  

  admin-users-app:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    container_name: administrador-usuarios-app
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      BD_URL: jdbc:postgresql://postgres-db:5432/administradorUsuariosDB
      BD_USER: postgres
      BD_PASSWORD: postgres
    networks:
      - postgres-network
networks:
  postgres-network:
    external: true
volumes:
  postgres_data: